# 站点配置
title: 我的博客
email: xiaomafeibeng2@gmail.com
description: 一个简约的个人博客
baseurl: ""
url: "https://xiaomafeibeng2.github.io"

# 社交媒体
twitter_username: 
github_username: 

# 构建设置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 主题设置
lang: zh-CN
timezone: Asia/Shanghai
